// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALt150lGnLbPQ652YDH2d2lLO_-QXJzD0',
    appId: '1:3743105992:web:e6f4c9b2e22d14599af6fd',
    messagingSenderId: '3743105992',
    projectId: 'vyapaarx-1',
    authDomain: 'vyapaarx-1.firebaseapp.com',
    storageBucket: 'vyapaarx-1.firebasestorage.app',
    measurementId: 'G-F4W8LX6DW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLaEjGA137sAc-_JY77asydn9MZPxon8',
    appId: '1:3743105992:android:13dde6217044d9bd9af6fd',
    messagingSenderId: '3743105992',
    projectId: 'vyapaarx-1',
    storageBucket: 'vyapaarx-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxByVEEpTjs7Bn8Op-fxWnrV8_vbctZ8',
    appId: '1:3743105992:ios:b1232adf6f3366449af6fd',
    messagingSenderId: '3743105992',
    projectId: 'vyapaarx-1',
    storageBucket: 'vyapaarx-1.firebasestorage.app',
    iosClientId:
        '3743105992-tap8k97sj028vheuhk689e6bgs85li20.apps.googleusercontent.com',
    iosBundleId: 'com.vyapaarx.vyapaarx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxByVEEpTjs7Bn8Op-fxWnrV8_vbctZ8',
    appId: '1:3743105992:ios:b1232adf6f3366449af6fd',
    messagingSenderId: '3743105992',
    projectId: 'vyapaarx-1',
    storageBucket: 'vyapaarx-1.firebasestorage.app',
    iosClientId:
        '3743105992-tap8k97sj028vheuhk689e6bgs85li20.apps.googleusercontent.com',
    iosBundleId: 'com.vyapaarx.vyapaarx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALt150lGnLbPQ652YDH2d2lLO_-QXJzD0',
    appId: '1:3743105992:web:673bb6be6464ac8b9af6fd',
    messagingSenderId: '3743105992',
    projectId: 'vyapaarx-1',
    authDomain: 'vyapaarx-1.firebaseapp.com',
    storageBucket: 'vyapaarx-1.firebasestorage.app',
    measurementId: 'G-1N5VC58MRZ',
  );
}
